menu_items:
  - location: application
    label:
      en: Asset Management System
      zh: 资产管理系统
    url: "apps/asset-management?theme={system_theme}"
    url_type: iframe
    background: "#f9f9f9|#e8e8e8"
    visible_to: ${Authorized_users}