services:
  asset-management:
    image: "nightcp/asset-management:${PLUGIN_VERSION}"
    volumes:
      - asset_management_data:/app/data
    restart: unless-stopped

volumes:
  asset_management_data: